### Hello world
GET http://localhost:3333/api/hello HTTP/1.1

### Register user
POST http://localhost:3333/api/users/register HTTP/1.1
Content-Type: application/json

{
    "name": "babehas",
    "username": "babehas183",
    "email": "babehas183@hopesx.com",
    "password": "Babehas183@",
    "bio": "Essa é a bio da babehas183."
}


### Get cookie
GET http://localhost:3333/api/auth/test-cookies HTTP/1.1

### Clear cookie
GET http://localhost:3333/api/auth/clear-cookies HTTP/1.1


### Login user
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "babehas183@hopesx.com",
    "password": "Babehas183@"
}


### Verify OTP
POST http://localhost:3333/api/auth/verify-otp HTTP/1.1
Content-Type: application/json

{
    "code": "812697"
}